AWSTemplateFormatVersion: '2010-09-09'
Description: BOOKFLOW - Tier 00 - CloudTrail Management events trail (S3 destination + KMS encrypted)
Parameters:
  ProjectName:
    Type: String
    Default: bookflow

Resources:
  Trail:
    Type: AWS::CloudTrail::Trail
    Properties:
      TrailName: !Sub ${ProjectName}-trail
      S3BucketName: !ImportValue
        Fn::Sub: ${ProjectName}-s3-audit-name
      KMSKeyId: !ImportValue
        Fn::Sub: ${ProjectName}-kms-cloudtrail-arn
      IncludeGlobalServiceEvents: true
      IsLogging: true
      IsMultiRegionTrail: true
      EnableLogFileValidation: true
      EventSelectors:
        - ReadWriteType: All
          IncludeManagementEvents: true
          DataResources: []

Outputs:
  TrailArn:
    Value: !GetAtt Trail.Arn
    Export:
      Name: !Sub ${ProjectName}-cloudtrail-arn
