---
# cicd/ansible/inventory/hosts.yml
# Ansible CN   (localhost )
# SSM Send-Command  CN    → localhost  

all:
  hosts:
    localhost:
      ansible_connection: local
      ansible_python_interpreter: /usr/bin/python3
