AWSTemplateFormatVersion: '2010-09-09'
Description: "BOOKFLOW - Tier 10 - VPC Peering: Egress <-> Data. inventory API ECS (Egress) -> RDS (Data) read access"
Parameters:
  ProjectName:
    Type: String
    Default: bookflow

Resources:
  Peering:
    Type: AWS::EC2::VPCPeeringConnection
    Properties:
      VpcId: !ImportValue { 'Fn::Sub': '${ProjectName}-vpc-egress-id' }
      PeerVpcId: !ImportValue { 'Fn::Sub': '${ProjectName}-vpc-data-id' }
      Tags: [{ Key: Name, Value: !Sub '${ProjectName}-peering-egress-data' }]

  RouteEgressToData:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !ImportValue { 'Fn::Sub': '${ProjectName}-rt-egress-public' }
      DestinationCidrBlock: 10.3.0.0/16
      VpcPeeringConnectionId: !Ref Peering

  RouteDataPrivateToEgress:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !ImportValue { 'Fn::Sub': '${ProjectName}-rt-data-private' }
      DestinationCidrBlock: 10.2.0.0/16
      VpcPeeringConnectionId: !Ref Peering

  RouteDataDbToEgress:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !ImportValue { 'Fn::Sub': '${ProjectName}-rt-data-db' }
      DestinationCidrBlock: 10.2.0.0/16
      VpcPeeringConnectionId: !Ref Peering

Outputs:
  PeeringId:
    Value: !Ref Peering
    Export: { Name: !Sub '${ProjectName}-peering-egress-data-id' }
